ALTER TABLE rotas ADD COLUMN IF NOT EXISTS numero_f1 TEXT;
ALTER TABLE rotas ADD COLUMN IF NOT EXISTS ajudante2_id INTEGER REFERENCES funcionarios(id);
ALTER TABLE rotas ADD COLUMN IF NOT EXISTS nf_url TEXT;