DROP TABLE IF EXISTS alertas CASCADE;
DROP TABLE IF EXISTS rotas CASCADE;
DROP TABLE IF EXISTS relatorios CASCADE;
DROP TABLE IF EXISTS funcionarios CASCADE;
DROP TABLE IF EXISTS operadores CASCADE;
DROP TABLE IF EXISTS bases CASCADE;
CREATE TABLE bases (id SERIAL PRIMARY KEY, nome TEXT NOT NULL, usuario TEXT UNIQUE NOT NULL, senha TEXT NOT NULL, cidade TEXT, is_admin INTEGER DEFAULT 0, ativo INTEGER DEFAULT 1, criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE operadores (id SERIAL PRIMARY KEY, base_id INTEGER NOT NULL REFERENCES bases(id), nome TEXT NOT NULL, usuario TEXT UNIQUE NOT NULL, senha TEXT NOT NULL, ativo INTEGER DEFAULT 1, criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE funcionarios (id SERIAL PRIMARY KEY, base_id INTEGER NOT NULL REFERENCES bases(id), nome TEXT NOT NULL, cargo TEXT NOT NULL CHECK(cargo IN ('motorista','ajudante')), cpf TEXT, ativo INTEGER DEFAULT 1, criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE relatorios (id SERIAL PRIMARY KEY, base_id INTEGER NOT NULL REFERENCES bases(id), data_referencia TEXT NOT NULL, postado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP, status TEXT DEFAULT 'enviado');
CREATE TABLE rotas (id SERIAL PRIMARY KEY, relatorio_id INTEGER NOT NULL REFERENCES relatorios(id), numero_rota TEXT NOT NULL, motorista_id INTEGER REFERENCES funcionarios(id), ajudante_id INTEGER REFERENCES funcionarios(id), qtd_saiu INTEGER DEFAULT 0, qtd_entregou INTEGER DEFAULT 0, qtd_devolveu INTEGER DEFAULT 0, valor_recebido NUMERIC(10,2) DEFAULT 0, valor_esperado NUMERIC(10,2) DEFAULT 0, mercadorias_faltando TEXT, desconto_equipe INTEGER DEFAULT 0, motivo_desconto TEXT, valor_desconto NUMERIC(10,2) DEFAULT 0, observacoes TEXT);
CREATE TABLE alertas (id SERIAL PRIMARY KEY, base_id INTEGER NOT NULL REFERENCES bases(id), data_referencia TEXT NOT NULL, tipo TEXT NOT NULL, mensagem TEXT, lido INTEGER DEFAULT 0, criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO bases (nome, usuario, senha, cidade, is_admin) VALUES ('DIRETORIA', 'admin', '$2b$10$WulI.8U7heOsf2AshyjxyegF8hK2qK18.MgZvr9MOG8w2be5BBj5m', 'Central', 1);
INSERT INTO bases (nome, usuario, senha, cidade, is_admin) VALUES ('Joao Paulo Master', 'joao.paulo@timingtransportes.com.br', '$2b$10$yGMYw01gA.JDl76Wa9EpZeZgLK7zo5akrtWeMvFHStA9rhng791dO', 'Central', 1);
INSERT INTO bases (nome, usuario, senha, cidade, is_admin) VALUES ('Base Sao Paulo', 'base_sp', '$2b$10$iT5aeLneeUsDs30YDyCGzulok4EElgIgaH1vMwIrnkXU0RIArMMUa', 'Sao Paulo', 0);
INSERT INTO bases (nome, usuario, senha, cidade, is_admin) VALUES ('Base Rio de Janeiro', 'base_rj', '$2b$10$3BnBEhpvhnhBZiSH6iGXHuMpb/VwBDX7jseVY1ePJCfYd5B57biSC', 'Rio de Janeiro', 0);
INSERT INTO bases (nome, usuario, senha, cidade, is_admin) VALUES ('Base Belo Horizonte', 'base_bh', '$2b$10$sL53eLBiBLV0ZryUeuCKRuebnt5u3WkUPgRvCjbiTp8WAxvInrR2e', 'Belo Horizonte', 0);
INSERT INTO bases (nome, usuario, senha, cidade, is_admin) VALUES ('Base Brasilia', 'base_bsb', '$2b$10$sPK7HGjXhn.GrO/2lmVdy.f0N3O9hluypvnxJEG8fQ0i34Tj7wXrm', 'Brasilia', 0);
INSERT INTO bases (nome, usuario, senha, cidade, is_admin) VALUES ('Base Salvador', 'base_ssa', '$2b$10$GfYVzgyHBLoVN4b4mjJX3Objt0urZiJSQbYlh0OoYH2BcMTax9Lhy', 'Salvador', 0);
SELECT id, nome, usuario, is_admin FROM bases;